"""

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

"""


def findTheDifference(self, s: str, t: str) -> str:
    counter_s = Counter(s)

    # Iterate through string t and find the character which is not in s.
    for ch in t:
        if ch not in counter_s or counter_s[ch] == 0:
            return ch
        else:
            # Once a match is found we reduce frequency left.
            # This eliminates the possibility of a false match later.
            counter_s[ch] -= 1
